site_name: Kedro-Dagster's documentation
site_url: https://gtauzin.github.io/kedro-dagster/
repo_name: gtauzin/kedro-dagster
repo_url: https://github.com/gtauzin/kedro-dagster

edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Introduction:
      - pages/introduction/index.md
  - Getting Started:
      - pages/getting-started/index.md
      - Installation: pages/getting-started/installation.md
      - Quickstart: pages/getting-started/quickstart.md
  - Tutorials:
      - pages/tutorials/index.md
      - Setting up: pages/tutorials/setting-up.md
  - Technical Documentation:
      - pages/technical/index.md
      - Project: pages/technical/project.md
      - Catalog: pages/technical/catalog.md
      - Nodes: pages/technical/nodes.md
      - Pipelines: pages/technical/pipelines.md
      - Hooks: pages/technical/hooks.md
  - API Reference:
      - pages/api/index.md
      - kedro_dagster: pages/api/kedro-dagster.md
  - Contributing:
      - pages/contributing/index.md
      - Code of Conduct: pages/contributing/code-of-conduct.md
      - Contributing Guide: pages/contributing/guide.md

theme:
  name: material
  custom_dir: docs/material/overrides

  features:
    - announce.dismiss
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight

  favicon: images/favicon.png
  logo: assets/logo.png

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: true

  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: google
            merge_init_into_class: true
            docstring_section_style: list
            separate_signature: true
            filters: ["!^_"]
            show_root_heading: true
            docstring_options:
              ignore_init_summary: true
              warn_unknown_params: false
              returns_named_value: false
          paths: [src]

extra:
  version:
    provider: mike

copyright: Copyright &copy; 2024 - 2025 Guillaume Tauzin
