"""Translation from Kedro to Dagtser."""

import os
from logging import getLogger
from pathlib import Path

import dagster as dg
from kedro.framework.project import find_pipelines, settings
from kedro.framework.session import KedroSession
from kedro.framework.startup import bootstrap_project
from kedro.utils import _find_kedro_project

from kedro_dagster.catalog import CatalogTranslator
from kedro_dagster.config import get_dagster_config
from kedro_dagster.dagster import (
    ExecutorCreator,
    LoggerTranslator,
    ScheduleCreator,
)
from kedro_dagster.kedro import KedroRunTranslator
from kedro_dagster.nodes import NodeTranslator
from kedro_dagster.pipelines import PipelineTranslator
from kedro_dagster.utils import get_mlflow_resource_from_config, is_mlflow_enabled

LOGGER = getLogger(__name__)


class KedroDagsterTranslator:
    """Translate Kedro project into Dagster.

    Args:
        project_path (str): The path to the Kedro project.
        env (str): A string representing the Kedro environment to use.
            If None, the default environment is used.
        conf_source (str): The path to the Kedro configuration source
            directory. If None, the default configuration source
            directory is used.

    Attributes:
        named_ops: A dictionary of named Dagster operations.
        named_assets: A dictionary of named Dagster assets
        named_resources: A dictionary of named Dagster resources.
        named_jobs: A dictionary of named Dagster jobs.
        named_schedules: A dictionary of named Dagster schedules.
        named_sensors: A dictionary of named Dagster sensors.
        named_loggers: A dictionary of named Dagster loggers.
        named_executors: A dictionary of named Dagster executors.

    """

    def __init__(
        self,
        project_path: Path | None = None,
        env: str | None = None,
        conf_source: str | None = None,
    ):
        self._project_path = project_path
        if project_path is None:
            self._project_path = _find_kedro_project(Path.cwd()) or Path.cwd()

        if env is None:
            default_run_env = settings._CONFIG_LOADER_ARGS["default_run_env"]
            env = os.getenv("KEDRO_ENV", default_run_env)

        self._env = env

        self.initialialize_kedro(conf_source=conf_source)

    @property
    def named_ops(self) -> dict[str, dg.OpDefinition]:
        """A dictionary mapping Kedro nodes' names to their corresponding Dagster ops."""
        return self._named_ops

    @property
    def named_assets(self) -> dict[str, dg.AssetSpec | dg.AssetsDefinition]:
        """A dictionary mapping Kedro nodes' names to their corresponding Dagster assets.

        The dictionary only includes the Kedro datasets that are not generated by any Kedro nodes.
        """
        return self._named_assets

    @property
    def named_resources(self) -> dict[str, dg.ResourceDefinition]:
        """A dictionary mapping Kedro datasets' names to their corresponding Dagster IO managers.

        The dictionary also includes the Kedro run resource and, optionally, the MLflow resource.
        """
        return self._named_resources

    @property
    def named_jobs(self) -> dict[str, dg.JobDefinition]:
        """A dictionary mapping Kedro pipelines' names to their corresponding Dagster jobs.

        Included pipelines are those defined in `dagster.yml`.
        """
        return self._named_jobs

    @property
    def named_schedules(self) -> dict[str, dg.ScheduleDefinition]:
        """A dictionary mapping Dagster schedule names to Dagster schedules.

        Included schedules are those defined in `dagster.yml`.
        """
        return self._named_schedules

    @property
    def named_sensors(self) -> dict[str, dg.SensorDefinition]:
        """A dictionary mapping Dagster sensor names names to Dagster sensors.

        Includes the sensor that triggers a run on pipeline error.
        """
        return self._named_sensors

    @property
    def named_loggers(self) -> dict[str, dg.LoggerDefinition]:
        """A dictionary mapping Kedro loggers' names to their corresponding Dagster loggers."""
        return self._named_loggers

    @property
    def named_executors(self) -> dict[str, dg.ExecutorDefinition]:
        """A dictionary mapping Dagster executor names to Dagster executors.

        Included schedules are those defined in `dagster.yml`.
        """
        return self._named_executors

    def initialialize_kedro(self, conf_source: str | None = None) -> None:
        """Initialize Kedro project.

        Args:
            conf_source: The path to the Kedro configuration source
            directory. If None, the default configuration source
            directory is used.

        """
        LOGGER.info("Initializing Kedro...")

        LOGGER.info("Bootstrapping project...")
        self._project_metadata = bootstrap_project(self._project_path)
        LOGGER.info(f"Project name: {self._project_metadata.project_name}")

        LOGGER.info("Creating session...")
        self._session = KedroSession.create(
            project_path=self._project_path,
            env=self._env,
            conf_source=conf_source,
        )

        self._session_id = self._session.session_id
        LOGGER.info(f"Session created with ID {self._session_id}")

        LOGGER.info("Loading context...")
        self._context = self._session.load_context()

        self._pipelines = find_pipelines()

        LOGGER.info("Kedro initialized.")

    # TODO: Allow translating a subset of the project
    # TODO: Allow to pass params that overwrite the dagster config
    def translate(self) -> None:
        """Translate Kedro project into Dagster.

        Calling this function sets the following attributes:
        - named_ops: A dictionary of named Dagster operations.
        - named_assets: A dictionary of named Dagster assets
        - named_resources: A dictionary of named Dagster resources.
        - named_jobs: A dictionary of named Dagster jobs.
        - named_schedules: A dictionary of named Dagster schedules.
        - named_sensors: A dictionary of named Dagster sensors.
        - named_loggers: A dictionary of named Dagster loggers.
        - named_executors: A dictionary of named Dagster executors.

        """
        LOGGER.info("Translating Kedro project into Dagster...")

        LOGGER.info("Loading configuration...")
        dagster_config = get_dagster_config(self._context)

        LOGGER.info("Creating run resources...")
        kedro_run_translator = KedroRunTranslator(
            context=self._context,
            project_path=str(self._project_path),
            env=self._env,
            session_id=self._session_id,
        )
        kedro_run_resource = kedro_run_translator._create_kedro_run_resource(
            pipeline_name="__default__",
            filter_params={},
            load_versions=None,
            extra_params=None,
        )
        self._named_resources = {"kedro_run": kedro_run_resource}

        LOGGER.info("Creating run sensor...")
        self._named_sensors = kedro_run_translator._translate_on_pipeline_error_hook()

        if is_mlflow_enabled():
            self._named_resources["mlflow"] = get_mlflow_resource_from_config(self._context.mlflow)

        LOGGER.info("Mapping loggers...")
        self.logger_creator = LoggerTranslator(
            dagster_config=dagster_config, package_name=self._project_metadata.package_name, pipelines=self._pipelines
        )
        self._named_loggers = self.logger_creator.translate_loggers()

        LOGGER.info("Translating catalog...")
        self.catalog_translator = CatalogTranslator(
            catalog=self._context.catalog,
            hook_manager=self._context._hook_manager,
            env=self._env,
        )
        named_io_managers = self.catalog_translator.translate_catalog()
        self._named_resources |= named_io_managers

        LOGGER.info("Translating nodes...")
        self.node_translator = NodeTranslator(
            pipelines=self._pipelines,
            catalog=self._context.catalog,
            hook_manager=self._context._hook_manager,
            session_id=self._session_id,
            named_resources=self._named_resources,
            env=self._env,
        )
        self._named_ops, self._named_assets = self.node_translator.translate_nodes()

        LOGGER.info("Creating executors...")
        self.executor_creator = ExecutorCreator(dagster_config=dagster_config)
        self._named_executors = self.executor_creator.create_executors()

        LOGGER.info("Translating pipelines...")
        self.pipeline_translator = PipelineTranslator(
            dagster_config=dagster_config,
            context=self._context,
            project_path=str(self._project_path),
            env=self._env,
            session_id=self._session_id,
            named_assets=self._named_assets,
            named_ops=self._named_ops,
            named_resources=self._named_resources,
            named_executors=self._named_executors,
        )
        self._named_jobs = self.pipeline_translator.translate_pipelines()

        LOGGER.info("Creating schedules...")
        self.schedule_creator = ScheduleCreator(dagster_config=dagster_config, named_jobs=self._named_jobs)
        self._named_schedules = self.schedule_creator.create_schedules()

        LOGGER.info("Kedro project translated into Dagster.")
