name: Run linter, tests, and generate coverage
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags-ignore: ["**"]
  pull_request:

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ckeck:
    name: Coverage tests for ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Add .local/bin to Windows PATH
        if: matrix.os == 'windows-latest'
        shell: bash
        run: echo "$USERPROFILE/.local/bin" >> $GITHUB_PATH

      - name: Install nox
        run: uv tool install --python-preference only-managed --python 3.13 nox

      - name: Install Python
        run: uv python install --python-preference only-managed ${{ matrix.python-version }}

      - name: Run checks
        run: nox -s fix

      - name: Run tests
        run: nox -s tests_coverage --python ${{ matrix.python-version }}
        env:
          DIFF_AGAINST: HEAD
          PYTEST_XDIST_AUTO_NUM_WORKERS: 0

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }} && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: '${{ github.workspace }}/junit.${{ matrix.python-version }}.xml'

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: '${{ github.workspace }}/coverage.${{ matrix.python-version }}.xml'
          env_vars: OS,PYTHON
          fail_ci_if_error: true
